In [ ]:
%pip install pandas openpyxl

Requirement already satisfied: pandas in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.3.2)
Requirement already satisfied: openpyxl in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in C:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
print("hello")

hello

In [5]:
import pandas as pd
df=pd.read_excel('C:/-----SEM4-----/projects/data eng/online_retail_II.xlsx')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [6]:
keys= [cols for cols in df.columns if df[cols].is_unique and df[cols].notna().all()]
print("primary key could be: ",keys)

primary key could be:  []

In [7]:
for col in df.columns:
    unique_count = df[col].nunique()
    total_count = len(df)
    missing_count = df[col].isna().sum()
    
    print(f"Column: '{col}'")
    print(f"  - Unique values: {unique_count} out of {total_count}")
    print(f"  - Missing values: {missing_count}\n")

Column: 'Invoice'
  - Unique values: 28816 out of 525461
  - Missing values: 0

Column: 'StockCode'
  - Unique values: 4632 out of 525461
  - Missing values: 0

Column: 'Description'
  - Unique values: 4681 out of 525461
  - Missing values: 2928

Column: 'Quantity'
  - Unique values: 825 out of 525461
  - Missing values: 0

Column: 'InvoiceDate'
  - Unique values: 25296 out of 525461
  - Missing values: 0

Column: 'Price'
  - Unique values: 1606 out of 525461
  - Missing values: 0

Column: 'Customer ID'
  - Unique values: 4383 out of 525461
  - Missing values: 107927

Column: 'Country'
  - Unique values: 40 out of 525461
  - Missing values: 0

In [8]:
# Check if the combination of Invoice and StockCode is 100% unique
is_composite_unique = not df.duplicated(subset=['Invoice', 'StockCode']).any()

print("Is Invoice + StockCode a valid primary key?:", is_composite_unique)

Is Invoice + StockCode a valid primary key?: False

In [9]:
df=pd.read_excel('C:/-----SEM4-----/projects/data eng/online_retail_II.xlsx')
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,525461.000000,525461,525461.000000,417534.000000
mean,10.337667,2010-06-28 11:37:36.845017856,4.688834,15360.645478
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 12:20:00,1.250000,13983.000000
50%,3.000000,2010-07-06 09:51:00,2.100000,15311.000000
75%,10.000000,2010-10-15 12:45:00,4.210000,16799.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,107.424110,NaN,146.126914,1680.811316

In [10]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64