In [28]:
%pip install seaborn

Requirement already satisfied: seaborn in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\moksh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# INVESTIGATION 1
#description :it is the dataset is of a hotel booking used from diff hotels there fore we are gonna
#work on understanding why there are decrease in booking and so on

# INVESTIGATION 1
description :it is the dataset is of a hotel booking used from diff hotels there fore we are gonna
             work on understanding why there are decrease in booking and so on

In [ ]:
#description
import pandas as pd
import numpy as np
df=pd.read_csv("C:/-----SEM4-----/projects/data eng/StayEase_Cleaned_Dataset.csv")
#now to check no of rows or coloumn we gotta use df.head() it usually gives first 5 rows starting from 0
df.head()

,hotel_type,booking_status,advance_booking_days,arrival_year,arrival_month,arrival_week,arrival_day,weekend_nights,weekday_nights,num_adults,...,avg_daily_rate,parking_spaces,special_requests,reservation_status,reservation_date,total_stay_nights,booking_season,family_booking,total_guests,is_long_stay
0,Luxury Resort,1,2,2016,June,24,5,1,0,2,...,109.0,0,1,Cancelled,04-06-2016,1.0,Summer,0.0,2.0,0.0
1,Urban Hotel,1,82,2016,September,38,15,0,3,2,...,149.4,0,1,Cancelled,12-09-2016,3.0,Autumn,0.0,2.0,0.0
2,Luxury Resort,0,62,2015,August,34,20,2,8,2,...,104.0,0,0,Checked-Out,30-08-2015,10.0,Summer,0.0,2.0,1.0
3,Urban Hotel,0,133,2016,May,21,17,0,3,2,...,105.3,0,0,Checked-Out,20-05-2016,3.0,Spring,0.0,2.0,0.0
4,Luxury Resort,1,87,2016,August,33,12,1,2,2,...,204.0,0,0,Cancelled,02-06-2016,3.0,Summer,1.0,3.0,0.0

In [ ]:
df.describe()
#just to understand the data  i meaan the total count or mean or std we can get it from .describe()

,booking_status,advance_booking_days,arrival_year,arrival_week,arrival_day,weekend_nights,weekday_nights,num_adults,num_children,num_infants,...,modifications,travel_agent_id,waiting_days,avg_daily_rate,parking_spaces,special_requests,total_stay_nights,family_booking,total_guests,is_long_stay
count,44010.000000,44010.000000,44010.000000,44010.000000,44010.000000,44010.000000,44010.000000,44010.000000,44010.000000,44010.000000,...,44010.000000,36829.000000,44010.000000,44010.000000,44010.000000,44010.000000,44009.000000,44009.000000,44009.000000,44009.000000
mean,0.331175,94.928471,2016.179664,26.959100,15.724222,0.957055,2.529243,1.861418,0.112793,0.008703,...,0.238128,88.932309,1.658100,104.472886,0.068871,0.626380,3.486287,0.085437,1.981776,0.126633
std,0.470641,100.572661,0.702268,13.456067,8.742672,1.002676,1.942625,0.488589,0.414360,0.102200,...,0.661240,111.786207,15.280731,45.786097,0.254579,0.812734,2.606468,0.279534,0.668135,0.332565
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,15.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,73.522500,0.000000,0.000000,2.000000,0.000000,2.000000,0.000000
50%,0.000000,61.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,13.000000,0.000000,97.000000,0.000000,0.000000,3.000000,0.000000,2.000000,0.000000
75%,1.000000,147.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,...,0.000000,240.000000,0.000000,127.000000,0.000000,1.000000,4.000000,0.000000,2.000000,0.000000
max,1.000000,709.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,3.000000,10.000000,9.000000,...,17.000000,535.000000,391.000000,256.500000,3.000000,5.000000,69.000000,1.000000,4.000000,1.000000

In [ ]:

checknull=[cols for cols in df.columns if df[cols].is_unique and df[cols].notna.all()]
print("the null:",checknull)
#this shows that there are no null values

the null: []

In [15]:
#now lets drop any duplicates if it exists
df.drop_duplicates()
df.head(2)

,hotel_type,booking_status,advance_booking_days,arrival_year,arrival_month,arrival_week,arrival_day,weekend_nights,weekday_nights,num_adults,...,avg_daily_rate,parking_spaces,special_requests,reservation_status,reservation_date,total_stay_nights,booking_season,family_booking,total_guests,is_long_stay
0,Luxury Resort,1,2,2016,June,24,5,1,0,2,...,109.0,0,1,Cancelled,04-06-2016,1.0,Summer,0.0,2.0,0.0
1,Urban Hotel,1,82,2016,September,38,15,0,3,2,...,149.4,0,1,Cancelled,12-09-2016,3.0,Autumn,0.0,2.0,0.0

In [ ]:
import numpy as np

#classification: now let us segregate them into numeric and names type
numeric= df.select_dtypes(include=['int64','float64']).columns.to_numpy
names= df.select_dtypes(include=['object','category']).columns.to_numpy
print("numeric types are: ",np.array(numeric))
print("name types are: ",np.array(names))

numeric types are:  <bound method IndexOpsMixin.to_numpy of Index(['booking_status', 'advance_booking_days', 'arrival_year',
       'arrival_week', 'arrival_day', 'weekend_nights', 'weekday_nights',
       'num_adults', 'num_children', 'num_infants', 'is_repeated_guest',
       'previous_cancellations', 'previous_bookings_not_canceled',
       'modifications', 'travel_agent_id', 'waiting_days', 'avg_daily_rate',
       'parking_spaces', 'special_requests', 'total_stay_nights',
       'family_booking', 'total_guests', 'is_long_stay'],
      dtype='object')>
name types are:  <bound method IndexOpsMixin.to_numpy of Index(['hotel_type', 'arrival_month', 'meal_plan', 'guest_country',
       'booking_segment', 'booking_channel', 'reserved_room', 'assigned_room',
       'deposit_type', 'corporate_id', 'customer_category',
       'reservation_status', 'reservation_date', 'booking_season'],
      dtype='object')>

In [ ]:
#now lets check for 
for col in df.columns:
    unique_count = df[col].nunique()
    total_count = len(df)
    missing_count = df[col].isna().sum()
    
    print(f"Column: '{col}'")
    print(f"  - Unique values: {unique_count} out of {total_count}")
    print(f"  - Missing values: {missing_count}\n")
#apparently there are no unique values therfore we can find a primary key but we can find combinations of uniqueness

Column: 'hotel_type'
  - Unique values: 2 out of 44010
  - Missing values: 0

Column: 'booking_status'
  - Unique values: 2 out of 44010
  - Missing values: 0

Column: 'advance_booking_days'
  - Unique values: 469 out of 44010
  - Missing values: 0

Column: 'arrival_year'
  - Unique values: 3 out of 44010
  - Missing values: 0

Column: 'arrival_month'
  - Unique values: 12 out of 44010
  - Missing values: 0

Column: 'arrival_week'
  - Unique values: 53 out of 44010
  - Missing values: 0

Column: 'arrival_day'
  - Unique values: 31 out of 44010
  - Missing values: 0

Column: 'weekend_nights'
  - Unique values: 14 out of 44010
  - Missing values: 0

Column: 'weekday_nights'
  - Unique values: 29 out of 44010
  - Missing values: 0

Column: 'num_adults'
  - Unique values: 4 out of 44010
  - Missing values: 0

Column: 'num_children'
  - Unique values: 5 out of 44010
  - Missing values: 0

Column: 'num_infants'
  - Unique values: 4 out of 44010
  - Missing values: 0

Column: 'meal_plan'
  - Unique values: 5 out of 44010
  - Missing values: 0

Column: 'guest_country'
  - Unique values: 153 out of 44010
  - Missing values: 0

Column: 'booking_segment'
  - Unique values: 7 out of 44010
  - Missing values: 0

Column: 'booking_channel'
  - Unique values: 5 out of 44010
  - Missing values: 0

Column: 'is_repeated_guest'
  - Unique values: 2 out of 44010
  - Missing values: 0

Column: 'previous_cancellations'
  - Unique values: 15 out of 44010
  - Missing values: 0

Column: 'previous_bookings_not_canceled'
  - Unique values: 52 out of 44010
  - Missing values: 0

Column: 'reserved_room'
  - Unique values: 10 out of 44010
  - Missing values: 0

Column: 'assigned_room'
  - Unique values: 12 out of 44010
  - Missing values: 0

Column: 'modifications'
  - Unique values: 15 out of 44010
  - Missing values: 0

Column: 'deposit_type'
  - Unique values: 3 out of 44010
  - Missing values: 0

Column: 'travel_agent_id'
  - Unique values: 280 out of 44010
  - Missing values: 7181

Column: 'corporate_id'
  - Unique values: 273 out of 44010
  - Missing values: 0

Column: 'waiting_days'
  - Unique values: 111 out of 44010
  - Missing values: 0

Column: 'customer_category'
  - Unique values: 4 out of 44010
  - Missing values: 0

Column: 'avg_daily_rate'
  - Unique values: 5355 out of 44010
  - Missing values: 0

Column: 'parking_spaces'
  - Unique values: 4 out of 44010
  - Missing values: 0

Column: 'special_requests'
  - Unique values: 6 out of 44010
  - Missing values: 0

Column: 'reservation_status'
  - Unique values: 3 out of 44010
  - Missing values: 0

Column: 'reservation_date'
  - Unique values: 901 out of 44010
  - Missing values: 1

Column: 'total_stay_nights'
  - Unique values: 36 out of 44010
  - Missing values: 1

Column: 'booking_season'
  - Unique values: 4 out of 44010
  - Missing values: 1

Column: 'family_booking'
  - Unique values: 2 out of 44010
  - Missing values: 1

Column: 'total_guests'
  - Unique values: 5 out of 44010
  - Missing values: 1

Column: 'is_long_stay'
  - Unique values: 2 out of 44010
  - Missing values: 1

In [27]:
#important features
import seaborn as sns

# Compute correlations between all columns and the target
correlations = df.corr()["target"].sort_values(ascending=False)

# Filter for features with a correlation strength greater than 0.1 or less than -0.1
important_corr = correlations[correlations.abs() > 0.1]
print(important_corr)

ValueError: could not convert string to float: 'Luxury Resort'